apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: library-app-ingress
spec:
  rules:
    - host: library.local
      http:
        paths:
          - path: /login
            pathType: Prefix
            backend:
              service:
                name: library-app-service
                port:
                  number: 9080
