apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: library-app-ingress
 annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_cookie_domain localhost library.local;
spec:
  rules:
    - host: library.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: library-app-service
                port:
                  number: 9080
