apiVersion: v1
kind: Service
metadata:
  name: library-app-service
spec:
  selector:
    app: library-app
  type: NodePort
  ports:
    - port: 9080        # Service port
      targetPort: 9080  # Container port
      nodePort: 30080   # Access port on your host
