apiVersion: v1
kind: Service
metadata:
  name: library-app-service
spec:
  selector:
    app: library-app
  ports:
    - protocol: TCP
      port: 9080       # port inside the cluster
      targetPort: 9080
  type: ClusterIP      
